GET http://actualize.co

###

GET https://data.sfgov.org/resource/jjew-r69b.json

###

GET http://api.openweathermap.org/data/2.5/weather?q=san francisco&units=imperial&appid=9beb296210c3171be00be7e99d0e7ba8

### Definitions

GET https://api.wordnik.com/v4/word.json/cat/definitions?limit=200&includeRelated=false&useCanonical=false&includeTags=false&api_key=ac6099e63826b8650f05e22c4cc08baa2f21668e3f16176fd

### Top Example

GET https://api.wordnik.com/v4/word.json/hedgehog/topExample?useCanonical=false&api_key=ac6099e63826b8650f05e22c4cc08baa2f21668e3f16176fd

### Pronunciations

GET https://api.wordnik.com/v4/word.json/hedgehog/pronunciations?useCanonical=false&limit=50&api_key=ac6099e63826b8650f05e22c4cc08baa2f21668e3f16176fd

### Audio

GET https://api.wordnik.com/v4/word.json/hedgehog/audio?useCanonical=false&limit=50&api_key=ac6099e63826b8650f05e22c4cc08baa2f21668e3f16176fd
